FROM nginx:1.21

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Simulating readiness probe failure
COPY ./readiness_probe.sh /usr/local/bin/readiness_probe.sh
RUN chmod +x /usr/local/bin/readiness_probe.sh

ENTRYPOINT ["/usr/local/bin/readiness_probe.sh"]
