apiVersion: v1
kind: Pod
metadata:
  name: fixed-readiness-probe-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 15
