apiVersion: v1
kind: Pod
metadata:
  name: selinux-apparmor-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'SELinux/AppArmor policy fixed' && sleep 1000"
  securityContext:
    seLinuxOptions:
      level: "s0:c0,c0"  # Fixed the SELinux context
