apiVersion: v1
kind: Pod
metadata:
  name: selinux-apparmor-violation-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      seLinuxOptions:
        level: "s0:c0,c1"
