apiVersion: v1
kind: Pod
metadata:
  name: selinux-apparmor-issue-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Simulating SELinux/AppArmor policy violation' && sleep 1000"
  securityContext:
    seLinuxOptions:
      level: "s0:c0,c1"  # Simulating a policy violation
