apiVersion: v1
kind: Pod
metadata:
  name: security-context-issue-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      runAsUser: 0  # Running as root (not recommended)
