apiVersion: v1
kind: Pod
metadata:
  name: dns-fixed-pod
spec:
  containers:
  - name: dns-test
    image: busybox
    command: ["sh", "-c", "nslookup kubernetes.default.svc.cluster.local"]  # Tests DNS resolution