apiVersion: v1
kind: Pod
metadata:
  name: dns-resolution-failure-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - "1.1.1.1"
