apiVersion: v1
kind: Pod
metadata:
  name: port-binding-issue-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 8081  # Correct port configuration
    command:
      - "sh"
      - "-c"
      - "echo 'Port binding fixed' && sleep 1000"
