FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    stress \
    && rm -rf /var/lib/apt/lists/*

# Simulating resource requests/limits mismatch
COPY ./resource_mismatch.sh /usr/local/bin/resource_mismatch.sh
RUN chmod +x /usr/local/bin/resource_mismatch.sh

ENTRYPOINT ["/usr/local/bin/resource_mismatch.sh"]
