apiVersion: v1
kind: Pod
metadata:
  name: resource-mismatch-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Resource mismatch fixed' && sleep 1000"
    resources:
      requests:
        memory: "200Mi"
        cpu: "500m"
      limits:
        memory: "500Mi"
        cpu: "500m"  # Fixed to align the limits with the requests
