apiVersion: v1
kind: Pod
metadata:
  name: resource-mismatch-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "400Mi"
        cpu: "400m"
