apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "500Mi"  # Increased memory limit
      requests:
        memory: "300Mi"  # Increased memory request
    command:
      - "sh"
      - "-c"
      - "stress --vm 1 --vm-bytes 200Mi --vm-hang 0"  # Should work with the increased memory
