apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "1Gi"
