apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "100Mi"  # Memory limit too low for workload
      requests:
        memory: "100Mi"
    command:
      - "sh"
      - "-c"
      - "stress --vm 1 --vm-bytes 200Mi --vm-hang 0"  # Memory stress to trigger OOM
