apiVersion: v1
kind: Pod
metadata:
  name: crashloopbackoff-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "exit 1"  # Command that causes the container to crash
