apiVersion: v1
kind: Pod
metadata:
  name: taints-tolerations-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Taints and tolerations fixed' && sleep 1000"
  tolerations:
    - key: "example-key"
      operator: "Equal"
      value: "example-value"
      effect: "NoExecute"  # Correct matching taint
