apiVersion: v1
kind: Pod
metadata:
  name: taints-tolerations-mismatch-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Simulating taints and tolerations mismatch' && sleep 1000"
  tolerations:
    - key: "example-key"
      operator: "Equal"
      value: "example-value"
      effect: "NoExecute"  # Toleration mismatch with taint
