apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler-fixed-deployment
spec:
  replicas: 3  # Reduced replicas to match available node resources
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - name: busybox
        image: busybox
