apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler-issue-deployment
spec:
  replicas: 100  # Too many replicas without enough nodes, causing autoscaler failure
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - name: busybox
        image: busybox
