apiVersion: v1
kind: Pod
metadata:
  name: cluster-autoscaler-issue-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "8Gi"
        cpu: "4"
      limits:
        memory: "10Gi"
        cpu: "5"
