apiVersion: v1
kind: Pod
metadata:
  name: cgroup-issue-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: "1000m"  # Adjusted resources for better scheduling
        memory: "2Gi"  # Increased memory
