apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-issue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-issue-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-issue  # PVC that cannot bind
