apiVersion: v1
kind: Pod
metadata:
  name: failed-resource-limits-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: "500m"  # Increased CPU and memory limits
        memory: "1Gi"  # Increased memory limit
