apiVersion: v1
kind: Pod
metadata:
  name: failed-resource-limits-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: "100m"
        memory: "500Mi"  # Limited resources causing pod to fail under load
