apiVersion: v1
kind: Pod
metadata:
  name: failed-resource-limits-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "10Gi"
        cpu: "10"
      limits:
        memory: "20Gi"
        cpu: "20"
