apiVersion: v1
kind: Pod
metadata:
  name: file-permissions-issue-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /data  # Corrected path with appropriate permissions
