apiVersion: v1
kind: Pod
metadata:
  name: fixed-file-permissions-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /mnt/data
      name: data-volume
    securityContext:
      fsGroup: 1000
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc
