apiVersion: v1
kind: Service
metadata:
  name: service-port-fixed
spec:
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 8080  # Correct port
      targetPort: 8080  # Fixed to match container's port
---
apiVersion: v1
kind: Pod
metadata:
  name: service-port-fixed-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 8080
    command:
      - "sh"
      - "-c"
      - "echo 'Service port fixed' && sleep 1000"
