apiVersion: v1
kind: Service
metadata:
  name: service-port-issue
spec:
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 8081  # Mismatched port
      targetPort: 8080  # Target port does not match
---
apiVersion: v1
kind: Pod
metadata:
  name: service-port-issue-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    ports:
    - containerPort: 8080
    command:
      - "sh"
      - "-c"
      - "echo 'Simulating service port mismatch' && sleep 1000"
