apiVersion: v1
kind: Pod
metadata:
  name: outdated-k8s-version-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Running on an outdated Kubernetes version' && sleep 1000"
