FROM ubuntu:20.04

# Install required tools
RUN apt-get update && apt-get install -y curl vim && rm -rf /var/lib/apt/lists/*

# Add misconfiguration scripts
COPY misconfigured_lb.sh /scripts/
COPY missing_ports_lb.sh /scripts/

# Set script permissions
RUN chmod +x /scripts/*.sh

CMD ["/bin/bash"]
