apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-fixed
spec:
  selector:
    app: my-app  # Correct label selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
