apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-issue
spec:
  selector:
    app: non-existent-app  # Wrong label selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
