apiVersion: v1
kind: Pod
metadata:
  name: wrong-container-command-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"  # Correct command
      - "-c"
      - "echo 'Wrong container command fixed' && sleep 1000"
