apiVersion: v1
kind: Pod
metadata:
  name: wrong-container-command-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "invalid-command"  # Invalid command
    command:
      - "sh"
      - "-c"
      - "echo 'Simulating wrong container command' && sleep 1000"
