apiVersion: v1
kind: Pod
metadata:
  name: disk-io-error-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /valid-path  # Corrected path
