apiVersion: v1
kind: Pod
metadata:
  name: fixed-disk-io-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - mountPath: /data
        name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
