apiVersion: v1
kind: Pod
metadata:
  name: disk-io-errors-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - mountPath: /data
        name: my-volume
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
