apiVersion: v1
kind: Pod
metadata:
  name: disk-io-error-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /nonexistent-path  # Invalid path leading to disk I/O errors
