apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-failure-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080  # Correct endpoint for health check
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
    command:
      - "sh"
      - "-c"
      - "echo 'Liveness probe fixed' && sleep 1000"
