apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-failure-pod
spec:
  containers:
  - name: busybox
    image: busybox
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 1
    command:
      - "sh"
      - "-c"
      - "echo 'Liveness probe failure' && sleep 1000"
