apiVersion: v1
kind: Pod
metadata:
  name: insufficient-resources-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        cpu: "500m"  # Adjusted resource request
        memory: "1Gi"
