apiVersion: v1
kind: Pod
metadata:
  name: insufficient-resources-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        cpu: "2"   # Exceeds available resources
        memory: "4Gi"
