FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Simulating node affinity issue
COPY ./node_affinity_issue.sh /usr/local/bin/node_affinity_issue.sh
RUN chmod +x /usr/local/bin/node_affinity_issue.sh

ENTRYPOINT ["/usr/local/bin/node_affinity_issue.sh"]
