apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-issue-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - valid-node  # Correct node hostname
