apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-issue-pod
spec:
  containers:
  - name: busybox
    image: busybox
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - non-existent-node  # Invalid node hostname
