apiVersion: v1
kind: Pod
metadata:
  name: service-account-permission-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Service account permission fixed' && sleep 1000"
  serviceAccountName: valid-service-account  # Service account with proper permissions
