apiVersion: v1
kind: Pod
metadata:
  name: service-account-permission-issue-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Simulating service account permission issue' && sleep 1000"
  serviceAccountName: invalid-service-account  # Service account does not have permissions
