apiVersion: v1
kind: Pod
metadata:
  name: network-connectivity-issue-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "curl google.com"  # Fails due to network restrictions
