apiVersion: v1
kind: Pod
metadata:
  name: crash-disk-space-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        storage: "1Gi"  # Reduced storage request
