apiVersion: v1
kind: Pod
metadata:
  name: fixed-crash-due-to-insufficient-disk-space-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: log-pvc
