apiVersion: v1
kind: Pod
metadata:
  name: crash-disk-space-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        storage: "10Gi"  # Excessive storage request leading to disk issues
