apiVersion: v1
kind: Pod
metadata:
  name: crash-due-to-insufficient-disk-space-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: log-pvc
