apiVersion: v1
kind: Pod
metadata:
  name: firewall-restriction-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "curl google.com"  # This should succeed once the firewall allows traffic
