apiVersion: v1
kind: Pod
metadata:
  name: fixed-firewall-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
  networkPolicy:
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
