apiVersion: v1
kind: Pod
metadata:
  name: firewall-restriction-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "curl google.com"  # Firewall restricts outgoing traffic
