apiVersion: v1
kind: Pod
metadata:
  name: pid-namespace-collision-fixed-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'PID namespace fixed' && sleep 1000"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    pid: Container  # Fixed PID namespace usage
