apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fixed
spec:
  rules:
  - host: valid-domain.com  # Valid host name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
