apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-issue
spec:
  rules:
  - host: non-existent-domain.com  # Invalid host name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
